update to golang v1.16.2
gardener/gardener-extension-provider-vsphere pull request #140
Opened 2021-03-26 09:38 UTC by MartinWeindel

**How to categorize this PR?**

/area control-plane
/kind task
/platform vsphere

**What this PR does / why we need it**:
Updating Golang to v1.16 to be in sync with gardener/gardener dependency.
Also replace usage of packr with new Go 1.16 embed feature.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
update to golang v1.16.2
```

2021-04-07 12:41 UTC, stoyanr requested changes
Golang has already been updated to 1.16.2 with #141, and a newer g/g version has already been vendored. This PR should be rebased on master and replaced by a much smaller PR.

2021-04-21 12:28 UTC, mandelsoft approved these changes

2021-04-21 12:59 UTC, MartinWeindel commented
@stoyanr 
friendly ping. Can you please review the changes requested?

2021-04-21 15:39 UTC, stoyanr approved these changes
/lgtm

2021-04-21 17:38 UTC, merged