Support for Kubernetes v1.23
gardener/gardener-extension-provider-vsphere pull request #201
Opened 2022-01-22 13:46 UTC by rfranzke

**How to categorize this PR?**

/area open-source usability
/kind enhancement
/platform vsphere
/exp intermediate
/topology garden seed shoot

**What this PR does / why we need it**:
This PR adds support for Kubernetes 1.23 to the extension.

**Which issue(s) this PR fixes**:
Part of gardener/gardener#5102

**Special notes for your reviewer**:
* :x: Depends on #200, hence, PR is in draft state.
* I have not validated the functionality as follows due to missing test/dev environment:
  * ❔ Create new clusters with versions < 1.23
  * ❔ Create new clusters with version  = 1.23
  * ❔ Upgrade old clusters from version 1.22 to version 1.23
  * ❔ Delete clusters with versions < 1.23
  * ❔ Delete clusters with version  = 1.23

**Release note**:

```feature user
The vSphere extension does now support shoot clusters with Kubernetes version 1.23. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md) before upgrading to 1.23. 
```

2022-01-24 19:57 UTC, rfranzke commented
/ready

2022-01-25 11:07 UTC, MartinWeindel requested changes
Changes look good, but one minor adjustment is needed after indirect conflict with PR #202.
See comment for method `ensurer.EnsureKubeletServiceUnitOptions`.

I have also tested:
 - [x] Create new clusters with versions < 1.23
 - [x] Create new clusters with version  = 1.23
 - [x] Upgrade old clusters from version 1.22 to version 1.23
 - [x] Delete clusters with versions < 1.23
 - [x] Delete clusters with version  = 1.23

There is a new issue with K8s v1.23. Creating and using persisting volumes is not working anymore. The field `spec.providerID` is not filled anymore in the `node` objects.

I have tried to resolve the issue with using a new version of the cloud-controller-manager ([cloud-provider-vsphere v1.23.0-alpha.1](https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.23.0-alpha.1)), but it made no difference.

2022-01-25 13:57 UTC, rfranzke commented on pkg/webhook/controlplane/ensurer.go
>  func (e *ensurer) EnsureKubeletServiceUnitOptions(ctx context.Context, gctx gcontext.GardenContext, kubeletVersion *semver.Version, new, old []*unit.UnitOption) ([]*unit.UnitOption, error) {
Thanks, done!

2022-01-25 13:58 UTC, rfranzke commented
> There is a new issue with K8s v1.23. Creating and using persisting volumes is not working anymore. The field spec.providerID is not filled anymore in the node objects which causes that the vsphere-csi-controller does not find the node anymore.

Interesting, do you think this is related to https://github.com/gardener/gardener-extension-provider-vsphere/pull/201/commits/72d69b0c76020b1448b5faa8478c8531d4b8e15b? Does it work without this change?

2022-01-26 08:28 UTC, MartinWeindel commented
> > There is a new issue with K8s v1.23. Creating and using persisting volumes is not working anymore. The field spec.providerID is not filled anymore in the node objects which causes that the vsphere-csi-controller does not find the node anymore.
> 
> Interesting, do you think this is related to [72d69b0](https://github.com/gardener/gardener-extension-provider-vsphere/commit/72d69b0c76020b1448b5faa8478c8531d4b8e15b)? Does it work without this change?

Yes, if the kubelet gets the `--cloud-provider=external` command line argument, the `spec.providerID` is filled again and using PVC works as expected.

2022-01-26 12:18 UTC, rfranzke commented
@MartinWeindel OK, thanks for checking. I've reverted this change and added a TODO instead.

2022-01-26 12:56 UTC, MartinWeindel approved these changes
/lgtm
Thank you!

2022-01-26 12:56 UTC, merged